spring:
  application:
    name: service-book
  config:
    import: configserver:http://config-server:8889/

  datasource:
    url: jdbc:mysql://mysql8:3306/db_book?serverTimezone=America/Santiago&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: sasa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

#---
#spring:
#  config.activate.on-profile: dev
#  config:
#    import: configserver:http://localhost:8889/
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#---
#spring:
#  config.activate.on-profile: prod
#  config:
#    import: configserver:http://config-server:8889/
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-service:8761/eureka


#  spring.sleuth.sampler.probability=1.0
#  spring.zipkin.base-url=http://localhost:9411/
#spring.zipkin.sender.type=rabbit

