server:
  port: 8081
spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/jihenaor/config-files
          search-paths: config-data-prod

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
